project_id = "hayrkclcxfaowyrqguuh"

[functions.whatsapp-recebedor]
verify_jwt = false

[functions.whatsapp-lembrete]
verify_jwt = false

[functions.webhook-pagamento]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.lembrete-diario]
verify_jwt = false

[functions.remarketing-lembrete]
verify_jwt = false

[functions.lembrete-noturno]
verify_jwt = false
